include_recipe 'git'
include_recipe 'odi-users'
include_recipe 'odi-pk'
include_recipe 'ruby-ng'
include_recipe 'chef-client::config'
include_recipe 'chef-client::upstart_service'
include_recipe 'odi-monitoring'
