---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  environments_path: test/environments
  data_bags_path: test/data_bags

platforms:
  - name: ubuntu-14.04

suites:
  - name: production
    provisioner:
      client_rb:
        environment: csvlint-prod
    run_list:
      - recipe[chef_csvlint::default]
    attributes:
      mysql:
        host: <%= `ipconfig getifaddr en0` %>
        password: csvlint
